service: lambdora

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: lambdora-http-api/build/distributions/lambdora-http-api-0.1.0-SNAPSHOT.zip

functions:
  ldpGet:
    handler: org.fcrepo.lambdora.ldp.GetHandler
    events:
      - http:
          path: /rest/{thepath+}
          method: get
  ldpPost:
    handler: org.fcrepo.lambdora.ldp.PostHandler
    events:
      - http:
          path: /rest/{thepath+}
          method: post

# Creates DynamoDB table named "objectTable" with primary key of "subject"
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: objectTable
        AttributeDefinitions:
          - AttributeName: subject
            AttributeType: S
        KeySchema:
          - AttributeName: subject
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
 
