service: lambdora

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: lambdora-http-api/build/distributions/lambdora-http-api-0.1.0-SNAPSHOT.zip

functions:
  ldpJersey:
    handler: org.fcrepo.lambdora.ldp.JerseyRequestHandler
    events:
      - http:
          path: /rest/{thepath+}
          method: any

# Creates DynamoDB table named "objectTable" with primary key of "name"
resources:
  Resources:
    resourceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RESOURCE
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          - AttributeName: triple
            AttributeType: S
          - AttributeName: predicate
            AttributeType: S
          - AttributeName: object
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
          - AttributeName: triple
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          - IndexName: predicateIndex
            KeySchema:
              - AttributeName: name
                KeyType: HASH
              - AttributeName: predicate
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - subject
                - object
              ProjectionType: INCLUDE
        GlobalSecondaryIndexes:
          - IndexName: objectIndex
            KeySchema:
              - AttributeName: object
                KeyType: HASH
              - AttributeName: predicate
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - subject
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
