service: lambdora

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: lambdora-http-api/build/distributions/lambdora-http-api-0.1.0-SNAPSHOT.zip

functions:
  ldpJersey:
    handler: org.fcrepo.lambdora.ldp.JerseyRequestHandler
    events:
      - http:
          path: /rest/{thepath+}
          method: any

# Creates DynamoDB table named "RESOURCE_TRIPLE" with primary, composite key of "resource_name" and "rdf_triple"
# This table also has two indexes (see comments below)
resources:
  Resources:
    resourceTripleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RESOURCE_TRIPLE
        AttributeDefinitions:
          - AttributeName: resource_name
            AttributeType: S
          - AttributeName: rdf_triple
            AttributeType: S
          - AttributeName: rdf_predicate
            AttributeType: S
          - AttributeName: rdf_object
            AttributeType: S
        KeySchema:
          - AttributeName: resource_name
            KeyType: HASH
          - AttributeName: rdf_triple
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        LocalSecondaryIndexes:
          # Index providing a secondary sort on rdf_predicate to allow querying by resource_name + rdf_predicate
          - IndexName: predicateIndex
            KeySchema:
              - AttributeName: resource_name
                KeyType: HASH
              - AttributeName: rdf_predicate
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - rdf_subject
                - rdf_object
              ProjectionType: INCLUDE
        GlobalSecondaryIndexes:
          # Index providing ability to query on referenced rdf_object and/or rdf_predicate
          - IndexName: objectIndex
            KeySchema:
              - AttributeName: rdf_object
                KeyType: HASH
              - AttributeName: rdf_predicate
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - rdf_subject
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
